env:
  es6: true
  node: true
  mocha: true
extends: airbnb-base
parser: babel-eslint
globals:
  fetch: true
rules:
  semi:
    - error
    - never
  no-console: 0
  import/prefer-default-export: 0
  class-methods-use-this: 0
